//create user
POST http://localhost:5000/users
Content-Type: application/json

{
    "username" : "Dannyyy",
    "email" : "Uhuy@gmail.com",
    "password": "12345678",
    "confPassword": "12345678",
    "role" : "admin"
}
###
// get all Users
GET http://localhost:5000/users

###
//getsinggle user
GET http://localhost:5000/users/77fbc749-f6f8-4146-938e-9d33c7b3a2ad

###
// update user
PATCH http://localhost:5000/users/77fbc749-f6f8-4146-938e-9d33c7b3a2ad
Content-Type: application/json
{
    "username" : "bismilah",
    "email" : "Uhuy@gmail.com",
    "password": "",
    "confPassword": "",
    "role" : "user"
}

###
//delete
DELETE PATCH http://localhost:5000/users/77fbc749-f6f8-4146-938e-9d33c7b3a2ad