//create user
POST http://localhost:5000/users
Content-Type: application/json

{
    "username" : "Rahman",
    "email" : "user@gmail.com",
    "password": "123456",
    "confPassword": "123456",
    "role" : "user"
}
###
// get all Users
GET http://localhost:5000/users

###
//getsinggle user
GET http://localhost:5000/users/77fbc749-f6f8-4146-938e-9d33c7b3a2ad

###
// update user
PATCH http://localhost:5000/users/9381a4f5-e79d-48ba-a5d9-84e89fe24fd4
Content-Type: application/json

{
    "username" : "Rahmann",
    "email" : "rahman@gmail.com",
    "password": "",
    "confPassword": "",
    "role" : "user"
}

###
//delete
DELETE http://localhost:5000/users/56c9022e-31be-415c-bbef-efe69081948b

###
//login admin
POST http://localhost:5000/login
Content-Type: application/json

{
    "email" : "admin@gmail.com",
    "password": "123456"
}

###
//login user
POST http://localhost:5000/login
Content-Type: application/json

{
    "email" : "rahman@gmail.com",
    "password": "123456"
}

###
GET http://localhost:5000/me

// logout
###
DELETE  http://localhost:5000/logout